#!/usr/bin/env python
'''
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
'''
import os
import sys

import PepLibGen
import os
import sys

package_loc = r'../../Peptide Library Package'
print "Path exists: ", os.path.isdir(package_loc)

#Make sure the locally stored PepLibGen is used, not the one on Pythonpath
#This is to allow old CycloPs tags in SVN use old version of PepLibGen
sys.path.insert(0, package_loc)
from setuptools import setup

APP = ['../CycloPs.py']
DATA_FILES = ['../zinc_output']
OPTIONS = {'argv_emulation': True, 'packages':['rdkit'], 
            'dylib_excludes':['libicuuc.50.dylib'],
            'excludes':['scipy', 'matplotlib']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
